= RNR(1)
:doctype: manpage
:author: Franco Bugnano
:man source: rnr
:man version: 1.0.5
:man manual: rnr manual
:revdate: 2021-05-03


== NAME
rnr - Console file manager


== SYNOPSIS
*rnr* [_OPTIONS_]


== DESCRIPTION
rnr(1) (RNR's Not Ranger) is a text based file manager that combines the best
features of
https://midnight-commander.org/[Midnight Commander] and
https://ranger.github.io/[Ranger]


== OPTIONS
*-h, --help*::
	Show command line options
*-V, --version*::
	Show program's version number and exit
*-P* _FILE_**, --printwd** _FILE_::
	Print last working directory to _FILE_
*-D* _FILE_**, --database** _FILE_::
	Specify database file to use (default: _$XDG_DATA_HOME/rnr/rnr.db_)
	If _FILE_ is the string _:memory:_ a fast, but volatile RAM based database is used.
*-n, --nodb*::
	Do not use database (Takes precedence over *-D*)
*-b, --nocolor*::
	Requests to run in black and white
*-d, --debug*::
	Activate debug mode


== KEY BINDINGS
=== GENERAL
*ESC*:: Return to normal mode (like Vim)
*q, Q, F10*:: Exit
*CTRL-R*:: Reload panels
*CTRL-U*:: Swap panels
*CTRL-O*:: Show console output
*CTRL-Q*:: Toggle quick view on other panel
*TAB*:: Change active panel
*ALT-I*:: Set the other panel to the current directory
*ALT-O*:: Set the other panel to the highlited directory
*v, F3*:: View file with the selected pager / Enter directory
*e, F4*:: Edit file/directory with the selected editor
*F7*:: Make directory

=== PANEL
*h, LEFT*:: Go to the parent directory
*j, DOWN*:: Go to the next list element
*k, UP*:: Go to the previous list element
*l, RIGHT, ENTER*:: Enter directory / Follow symlink / Open file with the selected opener
*o*:: Open archive as a read-only directory
*x*:: Execute selected file
*g, HOME*:: Go to the top of the list
*G, END*:: Go to the bottom of the list
*CTRL-B, PAGE UP*:: Go up a page in the list
*CTRL-F, PAGE DOWN*:: Go down a page in the list
*f, /*:: Filter list (fuzzy finder like https://github.com/junegunn/fzf[fzf])
*uf, u/*:: Remove filter from list
*BACKSPACE*:: Show/Hide hidden files

=== SORTING
*sn*:: Sort by Name
*sN*:: Sort by Name (Reverse)
*se*:: Sort by Extension
*sE*:: Sort by Extension (Reverse)
*sd*:: Sort by Date & Time
*sD*:: Sort by Date & Time (Reverse)
*ss*:: Sort by Size
*sS*:: Sort by Size (Reverse)

=== BOOKMARKS
**m**_KEY_:: Add current directory to the bookmark named _KEY_
**'**_KEY_:: Go to the bookmark named _KEY_
*''*:: Go to the previous directory (2 times ', not ")

=== RENAME
*r, cc, cw*:: Rename file (replace)
*ce*:: Rename file (replace before extension)
*i, I*:: Rename file (insert)
*a*:: Rename file (append before extension)
*A*:: Rename file (append after extension)

=== SELECT (TAG) FILES
*INSERT, SPACE*:: Toggle tag on selected file
***:: Toggle tag on all files
*+*:: Tag files that match the shell wildcard pattern
*-, \*:: Untag files that match the shell wildcard pattern
*uv*:: Untag all files

=== OPERATIONS ON TAGGED FILES
*F5*:: Copy tagged files (or selected file)
*F6*:: Move tagged files (or selected file)
*F8*:: Delete tagged files (or selected file)

=== SHELL
*:, !*:: Execute a shell command


== SUBSTITUTIONS
The following substitutions are available for the shell, mkdir, rename, copy and move commands:

_%f_:: The current file
_%n_:: The current file name without extension
_%e_:: The current file extension (including the leading .)
_%d_:: The full path of the current directory
_%b_:: The name of the current directory (basename)
_%s, %t_:: The tagged files
_%F_:: The file in the other panel
_%N_:: The name of the file in the other panel without extension
_%E_:: The extension of the file in the other panel (including the leading .)
_%D_:: The full path of the directory of the other panel
_%B_:: The name of the directory of the other panel (basename)
_%S, %T_:: The tagged files of the other panel
_%%_:: The % character

There is no need to enclose these substitutions in quotes

=== EXAMPLE

**!**mpv _%t_:: Opens the tagged files with mpv


== FILES
rnr(1) respects the XDG Base Directory specification.
If the _$XDG_CONFIG_HOME_ environment variable is not set, the default
_~/.config_ directory will be used
instead.

_$XDG_CONFIG_HOME/rnr/config.py_::
	The rnr(1) configuration file
_$XDG_CONFIG_HOME/rnr/bookmarks_::
	The currently saved bookmarks
_/usr/bin/rnr_::
	The main executable
_/usr/bin/rnrview_::
	The internal viewer as a standalone executable
_/usr/share/rnr/rnr.fish_::
	Copy this file to _~/.config/fish/functions/_ to cd to the last directory
	when using the fish shell
_/usr/share/rnr/rnr.sh_::
	Source this file in _~/.bashrc_ to cd to the last directory when using
	bash


== RESOURCES
GitHub: <https://github.com/bugnano/rnr>

PyPI: <https://pypi.org/project/rnr/>


== SEE ALSO
rnrview(1)


== COPYING
Copyright \(C) 2020-2021 Franco Bugnano. Free use of this software is
granted under the terms of the GNU General Public License (GPL).

